apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tags.datadoghq.com/env: 'dev'
    tags.datadoghq.com/service: 'postgres-db'
  annotations:
    ad.datadoghq.com/service.check_names: '["postgres"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: |
      [
        {
          "dbm": true,
          "host": "database-1.cqjno1n1tkvw.us-east-1.rds.amazonaws.com",
          "port": 5432,
          "username": "postgres",
          "password": "admin12345",
          "tags": [
            "dbinstanceidentifier: database-1"
          ]
        }
      ]      
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: postgres

